name: Release (reusable)

on:
  workflow_call:
    outputs:
      last_version:
        value: ${{ jobs.release.outputs.last_version }}
      version:
        value: ${{ jobs.release.outputs.version }}
      tag:
        value: ${{ jobs.release.outputs.tag }}
      released:
        value: ${{ jobs.release.outputs.released }}
      release_notes:
        value: ${{ jobs.release.outputs.release_notes }}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: read
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
      - name: Semantic Release
        id: semantic-release
        uses: cycjimmy/semantic-release-action@b12c8f6015dc215fe37bc154d4ad456dd3833c90 # v6.0.0
        with:
          extra_plugins: |
            conventional-changelog-conventionalcommits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      last_version: ${{ steps.semantic-release.outputs.last_release_version }}
      version: ${{ steps.semantic-release.outputs.new_release_version }}
      tag: ${{ steps.semantic-release.outputs.new_release_git_tag }}
      released: ${{ steps.semantic-release.outputs.new_release_published }}
      release_notes: ${{ steps.semantic-release.outputs.new_release_notes }}
